name: Jest Tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_TEST_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_TEST_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
        env:
          CI: true
          DATABASE_URL: ${{ secrets.POSTGRES_TEST_DB }}
